<script lang="ts">
import interfaceIcons from '@/assets/icons/interface.json'

// Locally bundled Lucide artwork; regenerated by yarn build:icons.
export const ICON_PATHS: Record<string, Array<{ tag: string; attrs: Record<string, string | undefined> }>> = interfaceIcons
export const ICON_NAMES = Object.keys(ICON_PATHS)
</script>

<script setup lang="ts">
interface Props {
  name: string
  size?: number
  weight?: number
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  size: 18,
  weight: 1.75,
  class: '',
})

defineOptions({ inheritAttrs: false })

const attrs = useAttrs()

function cx(...parts: Array<string | undefined | null | false>): string {
  return parts.filter(Boolean).join(' ')
}

const klass = computed(() => cx('ic', props.class, attrs.class as string | undefined))
const inner = computed(() => ICON_PATHS[props.name] || [])
</script>

<template>
  <svg
    v-bind="$attrs"
    aria-hidden="true"
    focusable="false"
    :width="size"
    :height="size"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    :stroke-width="weight"
    stroke-linecap="round"
    stroke-linejoin="round"
    :class="klass"
  >
    <Component
      :is="node.tag"
      v-for="(node, index) in inner"
      :key="index"
      v-bind="node.attrs"
    />
  </svg>
</template>
