interface Station {
  icon: string
  paths: string[]
}

const stations: Station[] = [
  { icon: 'ws-menu', paths: ['/products', '/categories', '/orders', '/places', '/qr-codes'] },
  { icon: 'ws-customers', paths: ['/loyalty', '/discounts', '/discounts/secret-word'] },
  { icon: 'ws-team', paths: ['/hr-employees', '/hr-departments', '/hr-contracts', '/hr-documents'] },
  { icon: 'ws-calendar', paths: ['/hr-leaves', '/hr-leave-balances', '/hr-leave-types'] },
  { icon: 'ws-target', paths: ['/hr-goals', '/hr-reviews', '/hr-events'] },
  { icon: 'ws-payroll', paths: ['/hr-salaries', '/hr-cash', '/hr-expenses', '/hr-expense-categories'] },
  { icon: 'ws-shift', paths: ['/shifts-analytics', '/shift-templates', '/analytics/shift-handover', '/audit'] },
  { icon: 'ws-finance', paths: ['/money-control', '/treasury', '/cashbox/categories', '/fiscalization'] },
  { icon: 'ws-analytics', paths: ['/reports/product-performance', '/analytics/product-statistics', '/analytics/menu-engineering', '/analytics/compare', '/forecast/tomorrow'] },
  { icon: 'ws-warehouse', paths: ['/warehouse', '/stock/items', '/stock/levels', '/stock/batches', '/stock/alerts'] },
  { icon: 'ws-delivery', paths: ['/stock/suppliers', '/stock/purchase-invoices', '/stock/purchase-orders', '/stock/receiving'] },
  { icon: 'ws-inventory', paths: ['/stock/counts', '/stock/adjustment-requests', '/stock/adjustments', '/stock/transactions'] },
  { icon: 'ws-transfer', paths: ['/stock/transfers', '/stock/locations', '/stock/reservations'] },
  { icon: 'ws-recipe', paths: ['/stock/recipes', '/stock/production-orders', '/stock/product-links'] },
  { icon: 'ws-catalog', paths: ['/stock/categories', '/stock/units', '/stock/variance-codes', '/stock/settings'] },
  { icon: 'ws-notification', paths: ['/notifications', '/notification-queue', '/notification-templates', '/notification-types', '/notification-settings'] },
  { icon: 'ws-settings', paths: ['/app-settings', '/settings/roles', '/users', '/sessions'] },
  { icon: 'ws-license', paths: ['/licensing/status', '/licensing/plans'] },
]

const pageIcons: Record<string, string> = {
  '/products': 'ws-product',
  '/categories': 'ws-catalog',
  '/orders': 'receipt',
  '/places': 'ws-dining',
  '/qr-codes': 'ws-qr',
  '/loyalty': 'ws-customers',
  '/discounts': 'ws-discount',
  '/discounts/secret-word': 'key',
  '/hr-employees': 'ws-team',
  '/hr-departments': 'dept',
  '/hr-contracts': 'document',
  '/hr-documents': 'folder',
  '/hr-leaves': 'ws-calendar',
  '/hr-leave-balances': 'calendar',
  '/hr-leave-types': 'list',
  '/hr-goals': 'target',
  '/hr-reviews': 'ws-target',
  '/hr-events': 'flag',
  '/hr-salaries': 'ws-payroll',
  '/hr-cash': 'wallet',
  '/hr-expenses': 'receipt',
  '/hr-expense-categories': 'tag',
  '/shifts-analytics': 'ws-shift',
  '/shift-templates': 'calendar',
  '/analytics/shift-handover': 'exchange',
  '/audit': 'shield',
  '/money-control': 'ws-finance',
  '/treasury': 'wallet',
  '/cashbox/categories': 'tag',
  '/fiscalization': 'ws-license',
  '/reports/product-performance': 'ws-analytics',
  '/analytics/product-statistics': 'bars',
  '/analytics/menu-engineering': 'ws-menu',
  '/analytics/compare': 'share',
  '/forecast/tomorrow': 'trend',
  '/warehouse': 'ws-warehouse',
  '/stock/items': 'ws-catalog',
  '/stock/levels': 'bars',
  '/stock/batches': 'package',
  '/stock/alerts': 'alert',
  '/stock/suppliers': 'building',
  '/stock/purchase-invoices': 'receipt',
  '/stock/purchase-orders': 'ws-delivery',
  '/stock/receiving': 'inbox',
  '/stock/counts': 'ws-inventory',
  '/stock/adjustment-requests': 'file',
  '/stock/adjustments': 'sliders',
  '/stock/transactions': 'history',
  '/stock/transfers': 'ws-transfer',
  '/stock/locations': 'ws-location',
  '/stock/reservations': 'lock',
  '/stock/recipes': 'ws-recipe',
  '/stock/production-orders': 'gear',
  '/stock/product-links': 'link',
  '/stock/categories': 'grid',
  '/stock/units': 'weight',
  '/stock/variance-codes': 'file',
  '/stock/settings': 'sliders',
  '/notifications': 'ws-notification',
  '/notification-queue': 'inbox',
  '/notification-templates': 'copy',
  '/notification-types': 'bell',
  '/notification-settings': 'sliders',
  '/app-settings': 'ws-settings',
  '/settings/roles': 'shield',
  '/users': 'userok',
  '/sessions': 'ws-session',
  '/licensing/status': 'ws-license',
  '/licensing/plans': 'key',
}

export function workspaceForPath(path: string): Station {
  const matches = stations.flatMap(station => station.paths
    .filter(candidate => path === candidate || path.startsWith(`${candidate}/`))
    .map(candidate => ({ station: { ...station, icon: pageIcons[candidate] ?? station.icon }, length: candidate.length })))

  return matches.sort((a, b) => b.length - a.length)[0]?.station ?? { icon: 'ws-settings', paths: [] }
}
